
matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "8"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint
    - stage: "WebPack"
      os: osx
      env:
        - Platform="IOS 11"
      osx_image: xcode9.2
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      script: cd demo && npm run build.plugin && npm i && npm run ns-bundle --ios --build-app --uglify
    - language: android
      os: linux
      env:
        - Platform="Android 27"
      jdk: oraclejdk8
      before_install: nvm install stable
      script: - cd demo && npm run build.plugin && npm i
              - travis_wait travis_retry npm run ns-bundle --android --build-app
    - stage: "Tests"
      os: osx
       env:
        - TestVersion="latest"
      osx_image: xcode9.2
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      before_script: cd src
      script: travis_wait travis_retry npm run test.ios
    - language: android
      os: linux
       env:
        - TestVersion="latest"
      jdk: oraclejdk8
      before_install: nvm install stable
      before_script:
        - cd src
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      script: travis_wait travis_retry npm run test.android
    - stage: "Build"
      env:
        - BuildAndroid="27"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install stable
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build android
    - os: osx
      env:
        - BuildiOS="11"
        - Xcode="9.2"
      osx_image: xcode9.2
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
