
matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "8"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint
    - stage: "WebPack"
      os: osx
      env:
        - BuildiOS="11"
        - Xcode="9.2"
      osx_image: xcode9.2
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      script: cd demo && npm run build.plugin && npm i && npm run ns-bundle --ios --build-app --uglify
    - language: android
      os: linux
      env:
         - BuildAndroid="26"
      jdk: oraclejdk8
      before_install: nvm install stable
      script: cd demo && npm run build.plugin && npm i && npm run ns-bundle --android --build-app
    - stage: "Tests"
      os: osx
      env:
         - iOS="UnitTests"
      osx_image: xcode9.2
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      script:
        - cd src && npm i && npm run tsc && npm run tslint && cd ../demo && tns build ios
        - travis_wait travis_retry tns test ios --justlaunch
    - language: android
      os: linux
      env:
         - Android="UnitTests"
      jdk: oraclejdk8
      before_install: nvm install stable
      before_script:
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      script:
        - cd src && npm i && npm run tsc && npm run tslint && cd ../demo && tns build android
        - travis_wait travis_retry tns test android --justlaunch
    - stage: "Build"
      env:
         - BuildAndroid="26"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install stable
      script:
        - cd src && npm i && npm run tsc && cd ../demo
        - travis_wait travis_retry tns build android
    - os: osx
      env:
        - BuildiOS="11"
        - Xcode="9.2"
      osx_image: xcode9.2
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      script:
        - cd src && npm i && npm run tsc && cd ../demo
        - travis_wait travis_retry tns build ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
